version: '3.4'

services:
  codeparts:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "7178:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro