// <auto-generated />
using System;
using CodeParts.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeParts.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230404104935_addNullableFields")]
    partial class addNullableFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeParts.Data.TableModel.AccountDb", b =>
                {
                    b.Property<string>("login")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .HasColumnType("character varying")
                        .HasColumnName("email");

                    b.Property<string>("nickname")
                        .HasColumnType("character varying")
                        .HasColumnName("nickname");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("password");

                    b.Property<short?>("role")
                        .HasColumnType("smallint")
                        .HasColumnName("role");

                    b.HasKey("login");

                    b.HasIndex("login");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("CodeParts.Data.TableModel.CodeDb", b =>
                {
                    b.Property<long?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pk_code_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long?>("id"));

                    b.Property<string>("accountLogin")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("fk_account_login");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("content");

                    b.Property<string>("tags")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("tags");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("title");

                    b.HasKey("id");

                    b.HasIndex("accountLogin");

                    b.ToTable("content", (string)null);
                });

            modelBuilder.Entity("CodeParts.Data.TableModel.CodeDb", b =>
                {
                    b.HasOne("CodeParts.Data.TableModel.AccountDb", "Account")
                        .WithMany("Posts")
                        .HasForeignKey("accountLogin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CodeParts.Data.TableModel.AccountDb", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
